#!/bin/sh

set -e

if ! command -v gitleaks &> /dev/null; then
  echo "WARN: Gitleaks not installed!"
  exit 0
fi

if grep -q whitelist .gitleaks.toml &> /dev/null; then
  branch=$(git rev-parse --abbrev-ref HEAD)
  commits="$(git log origin/master..HEAD --oneline | wc -l | xargs)"

  if [ "$commits" -eq 0 ]; then
    echo "WARN: No commits different from origin/master - skipping gitleaks..."
    exit 0
  fi

  gitleaks -v \
           --repo-path . \
           --config .gitleaks.toml \
           --branch "$branch" \
           --depth "$commits"
else
  echo "WARN: Gitleaks config not found - using defaults..."
  gitleaks -v --repo-path .
fi
