source-file ~/.tmux.conf

# byobu refreshes its status bar more frequently
set-option -g status-interval 3

# reload binds must point to this file, not ~/.tmux.conf
unbind r
bind r source-file ~/.byobu/.tmux.conf \; display "Reloaded"
bind C-r source-file ~/.byobu/.tmux.conf \; display "Reloaded"
