BYOBU_DARK=black
BYOBU_LIGHT=white
BYOBU_ACCENT=magenta
BYOBU_HIGHLIGHT=red
MONOCHROME=0

# OSX-specific
#BYOBU_DARK="\#333333"
#BYOBU_LIGHT="\#EEEEEE"
#BYOBU_ACCENT="\#75507B"
#BYOBU_HIGHLIGHT="\#DD4814"
